export const ERROR_INVALID_DATA: number = 400;
export const ERROR_NOT_FOUND: number = 404;
export const REQUEST_SUCCESS: number = 200;
export const UNAUTHORIZED_ERROR: number = 401;
export const FORBIDDEN_ERROR: number = 403;
export const CREATED_SUCCESS: number = 201;
export const CONFLICT_ERROR: number = 409;
export const PICTURE_URL_REG_EXP = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/;
export const OBJECTID_REG_EXP = /^[a-f\d]{24}$/i;
